"""initial schema: filings, filing_sections, doc_chunks, golden_qa

Revision ID: ed0612ed3b38
Revises: 
Create Date: 2026-07-09 01:11:02.918009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ed0612ed3b38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_cik', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('form_type', sa.String(length=16), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('accession_number', sa.String(length=32), nullable=False),
    sa.Column('filing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('ingestion_status', sa.String(length=32), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("ingestion_status in ('pending','ocr_fallback','schema_drift_flagged','indexed','failed')", name='ck_filings_ingestion_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number', name='uq_filings_accession_number')
    )
    op.create_index(op.f('ix_filings_company_cik'), 'filings', ['company_cik'], unique=False)
    op.create_table('golden_qa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=False),
    sa.Column('requires_graph', sa.Boolean(), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doc_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('ocr_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_chunks_filing_id'), 'doc_chunks', ['filing_id'], unique=False)
    op.create_table('filing_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('section_name', sa.String(length=255), nullable=False),
    sa.Column('section_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filing_sections_filing_id'), 'filing_sections', ['filing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filing_sections_filing_id'), table_name='filing_sections')
    op.drop_table('filing_sections')
    op.drop_index(op.f('ix_doc_chunks_filing_id'), table_name='doc_chunks')
    op.drop_table('doc_chunks')
    op.drop_table('golden_qa')
    op.drop_index(op.f('ix_filings_company_cik'), table_name='filings')
    op.drop_table('filings')
    # ### end Alembic commands ###
